export const CREATE_POST_INIT = "CREATE_POST_INIT";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";

export const GET_POSTS_INIT = "GET_POSTS_INIT";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAILURE = "GET_POSTS_FAILURE";

export const POST_COMMENT_INIT = "POST_COMMENT_INIT";
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const POST_COMMENT_FAILURE = "POST_COMMENT_FAILURE";

export const EDIT_COMMENT_INIT = "EDIT_COMMENT_INIT";
export const EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS";
export const EDIT_COMMENT_FAILURE = "EDIT_COMMENT_FAILURE";

export const DELETE_COMMENT_INIT = "DELETE_COMMENT_INIT";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAILURE = "DELETE_COMMENT_FAILURE";

export const LIKE_POST_INIT = "LIKE_POST_INIT";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_FAILURE = "LIKE_POST_FAILURE";

export const DELETE_POST_INIT = "DELETE_POST_INIT";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";

export const DISLIKE_POST_INIT = "DISLIKE_POST_INIT";
export const DISLIKE_POST_SUCCESS = "DISLIKE_POST_SUCCESS";
export const DISLIKE_POST_FAILURE = "DISLIKE_POST_FAILURE";

export const FETCH_POST_INIT = "FETCH_POST_INIT";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAILURE = "FETCH_POST_FAILURE";

export const ADD_TITLE = "ADD_TITLE";
export const ADD_CONTENT = "ADD_CONTENT";

export const INIT_NOTIFICATION = "INIT_NOTIFICATION";
export const NOTIFICATION_SUCCESS = "NOTIFICATION_SUCCESS";
export const NOTIFICATION_FAILURE = "NOTIFICATION_FAILURE";

export const INIT_COMMENT_UPDATES = "INIT_COMMENT_UPDATES";
export const COMMENT_UPDATES_SUCCESS = "COMMENT_UPDATES_SUCCESS";
export const COMMENT_UPDATES_FAILURE = "COMMENT_UPDATES_FAILURE";

export const REPOST_POST_INIT = "REPOST_POST_INIT";
export const REPOST_POST_SUCCESS = "REPOST_POST_SUCCESS";
export const REPOST_POST_FAILURE = "REPOST_POST_FAILURE";

export const UNREPOST_POST_INIT = "UNREPOST_POST_INIT";
export const UNREPOST_POST_SUCCESS = "UNREPOST_POST_SUCCESS";
export const UNREPOST_POST_FAILURE = "UNREPOST_POST_FAILURE";

export const COMMENT_REPLY_INIT = "COMMENT_REPLY_INIT";
export const COMMENT_REPLY_SUCCESS = "COMMENT_REPLY_SUCCESS";
export const COMMENT_REPLY_FAILURE = "COMMENT_REPLY_FAILURE";
