export const SIGN_UP_INIT = "SIGN_UP_INIT";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const FETCH_AUTO_LOGIN = "FETCH_AUTO_LOGIN";
export const FETCH_AUTO_LOGIN_SUCCESS = "FETCH_AUTO_LOGIN_SUCCESS";
export const FETCH_AUTO_LOGIN_FAILURE = "FETCH_AUTO_LOGIN_FAILURE";

export const LOG_OUT_INIT = "LOG_OUT_INIT";
export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS";
export const LOG_OUT_FAILURE = "LOG_OUT_FAILURE";
