export const SIGN_UP_INIT = "SIGN_UP_INIT";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const EMAIL_CONFIRMATION_INIT = "EMAIL_CONFIRMATION_INIT";
export const EMAIL_CONFIRMATION_SUCCESS = "EMAIL_CONFIRMATION_SUCCESS";
export const EMAIL_CONFIRMATION_FAILURE = "EMAIL_CONFIRMATION_FAILURE";

export const FETCH_AUTO_LOGIN = "FETCH_AUTO_LOGIN";
export const FETCH_AUTO_LOGIN_SUCCESS = "FETCH_AUTO_LOGIN_SUCCESS";
export const FETCH_AUTO_LOGIN_FAILURE = "FETCH_AUTO_LOGIN_FAILURE";

export const LOG_OUT_INIT = "LOG_OUT_INIT";
export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS";
export const LOG_OUT_FAILURE = "LOG_OUT_FAILURE";

export const LOG_IN_INIT = "LOG_IN_INIT";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAILURE = "LOG_IN_FAILURE";

export const GET_CURRENT_USER = "GET_CURRENT_USER";

export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAILURE = "GET_USER_PROFILE_FAILURE";

export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAILURE = "UPDATE_USER_PROFILE_FAILURE";

export const ADD_USERNAME = "ADD_USERNAME";
export const ADD_EMAIL = "ADD_EMAIL";
export const ADD_PASSWORD = "ADD_PASSWORD";

export const INIT_LOGIN = "INIT_LOGIN";
