version: "3.9"
services:
  frontend:
    image: ${FRONTEND_DOCKER_IMAGE}
    restart: always
    volumes:
      - $PWD/../packages/front-end/envs/prod.json:/config.json

  nginx:
    image: nginx:1.23.3
    restart: always
    volumes:
      - $PWD/nginx/conf.d:/etc/nginx/conf.d
      - $PWD/nginx/tls:/tls-fullchain.crt
      - $PWD/nginx/tls:/tls-private.key
    depends_on:
      - frontend
    ports:
      - 443:443
      - 80:80
