on:
  - push

jobs:
  build:
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      VM_SSH_KEY: ${{ secrets.VM_SSH_KEY }}

    runs-on: ${{matrix.runs-on}}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build
        run: make build

      - name: Deploy
        run: make deploy
